version: '3.8'

services:
  app:
    build: .
    ports:
      - "6000:6000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}  
    volumes:
      - .:/app
      - /app/node_modules  
    command: sh -c "npm install && npm run dev"  

 

volumes:

